### ISSUE TITLE
api:schema error

### ISSUE THREAD

**Issue by RobinRadic** [anomalylabs/streams#105]
some property values are null
as workaround i applied array_filter

[streams] src/Stream/StreamSchema.php (Lines 32-38)

```

    public function object(): Schema
    {
        // @todo figure out why some property values are null, as workaround i applied array_filter
        $props=array_filter($this->properties());
        return Schema::object($this->stream->id)
            ->properties(...$props);
    }
```

[Open in IDE](https://api.codestream.com/c/Ya-f2HF1wklrPBqY/k2-QiXKBQkKLGBkhl6uLoA?marker=61bf983effa2cf65e33edd8b&ide=default&src=GitHub)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by RyanThompson** [comment]
I think this was due to missing field schemas - cannot reproduce anymore but let's get a specific use case (dump streams from the project here) if this occurs again.
