### ISSUE TITLE
API Schema Generator

### ISSUE THREAD

**Issue by RyanThompson** [anomalylabs/streams#106]
### API Schema Responsibilities:

- [ ] Generate an API schema.
- [ ] Generate Swagger documentation.

**Comment by RobinRadic** [comment]
Having self-valildating, code completing json files (most editors understand this)
```json 
{
  "$schema": "path/to/stream.schema.json",
  "config":{}
  "fields": {}
}
```
And it would be great to validate the json streams files against their schemas at runtime too
- [`justinrainbow/json-schema`](https://github.com/justinrainbow/json-schema)
- [`opis/json-schema`](https://opis.io/json-schema/2.x/)

Opis seems like a good one.

Also [league/openapi-psr7-validator](https://github.com/thephpleague/openapi-psr7-validator)

**Comment by RobinRadic** [comment]
It also seems to me like a good idea to add [HTTP tests](https://laravel.com/docs/8.x/http-tests#testing-json-apis). Ones that have the openapi spec ingrained with like [league/openapi-psr7-validator](https://github.com/thephpleague/openapi-psr7-validator). Something like a trait that allows validating requests inside a test. Should be super simple but very effective.

**Comment by RyanThompson** [comment]
Got fields/types refactored which is also a precursor to this.

**Comment by RyanThompson** [comment]
> Having self-valildating, code completing json files (most editors understand this)
> 
> ```json
> {
>   "$schema": "path/to/stream.schema.json",
>   "config":{}
>   "fields": {}
> }
> ```
> 
> And it would be great to validate the json streams files against their schemas at runtime too
> 
> * [`justinrainbow/json-schema`](https://github.com/justinrainbow/json-schema)
> * [`opis/json-schema`](https://opis.io/json-schema/2.x/)
> 
> Opis seems like a good one.
> 
> Also [league/openapi-psr7-validator](https://github.com/thephpleague/openapi-psr7-validator)

I would hesitate to validate at runtime just because of performance. Perhaps a `streams:validate` command.

**Comment by RyanThompson** [comment]
API command is all that is left.

**Comment by RyanThompson** [comment]
This is done.
