### ISSUE TITLE
Array merges, double rules. 

### ISSUE THREAD

**Issue by RobinRadic** [anomalylabs/streams#107]
call this a workaround or fix?

[streams] src/Stream/Stream.php (Lines 492-501)

```

            // @todo the double rules bug happens here, solved down below with a array_unique
            if ($fieldTypeRules = $field->type()->rules()) {
                $rules[$handle] = array_merge(
                    Arr::pull($rules, $handle, []),
                    $fieldTypeRules
                );
            }
            $rules[$handle] = array_unique($rules[$handle]);

```

[Open in IDE](https://api.codestream.com/c/Ya-f2HF1wklrPBqY/BVc4lAKxTLW5hYusD-RTnw?marker=61cacb1eb6ca983c42c1e872&ide=default&src=GitHub)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by RyanThompson** [comment]
This will be tightened up into fields-only but resolved here: https://github.com/laravel-streams/streams-core/commit/5830ae1fea73aaa30b0d2ec3e340d906b682a2ee
