### ISSUE TITLE
PatchEntry id removal & validation

### ISSUE THREAD

**Issue by RobinRadic** [anomalylabs/streams#108]
PatchEntry.php
I have removed some code in-between to show the problem. 
- id gets removed from payload
- entry instance is created (does have an id)
- payload attributes are set on the entry instance
- gets validated, fails. "The id has already been taken"

```php
        $payload->remove('id');
        $instance = Streams::entries($stream)->find($entry);
        $instance->loadPrototypeAttributes($payload->all());
        $validator = Streams::make($stream)->validator($instance);
        if ($validator->passes()) {
            Streams::repository($stream)->save($instance);
        }
```

Think its possible to validate that payload instead of instance, and if passes, set payload attributes on entry instance? Probably. What about removing the id like
```php
        $stream = Streams::make($stream);
        $keyName = $stream->getIdAttribute();
        $payload->remove($keyName);
```

**Comment by RobinRadic** [comment]
```php
        $validator = Streams::make($stream)->validator($payload->all());

        if ($validator->passes()) {
            Streams::repository($stream)->save($instance);
        }
        $instance->loadPrototypeAttributes($payload->all());
```
"The id field is required"

**There needs to be segregation between create and update rules.**

**Comment by RyanThompson** [comment]
This has been resolved, albeit not in an ideal way, the functionality is there to preserve and tuck away nicely when that time comes. Functionality correct.
