### ISSUE TITLE
composer.lock

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams#12]
I think the best would be to commit the composer.lock together

**Comment by huglester** [comment]
I also think, we would add program versions, by default to composer json, like:
swiftmailer/swiftmailer: ~5.3.*
twig/twig: ~1.16.*

and so on? what do you think? 


together with composer.lock it will make perfect combo, with stable packages, faster install etc

Thanks

**Comment by RyanThompson** [comment]
One down: https://github.com/anomalylabs/streams/commit/fdf6ee11ce15946bd4e16afb2f24019e9169976b

**Comment by RyanThompson** [comment]
PR for the second suggestion if you could?

**Comment by RyanThompson** [comment]
Do it on streams and Ill merge to PyroCMS

**Comment by huglester** [comment]
I am trying to gather all packages pyrocms installed and gather their versions.... gimme 20mins or something like that

**Comment by RyanThompson** [comment]
Perfect thank you!


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by huglester** [comment]
Omg, yesterday pcked everything and today somehow deleted... omfg:))) will retry now

but my observation are- we should require minimum required version.

And after playing with all that stuff, I figured out, that probably best is just to add 'prefer-stable' ?

**Comment by RyanThompson** [comment]
Ya we are at the point where we can probably do that - keep in mind we are still on old commits of Laravel 5 and Illuminate/Html though too.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by huglester** [comment]
I am now playing with prefer stable .. so far installer looks like this: http://pic.webas.lt/webas.lt-krnHqezYG8.png 

I'all see how installer goes after that etc, if ok, I'll pull request in short time

**Comment by RyanThompson** [comment]
Ok cool - ya update and make sure you can still install and all that and we’re good to go!

Thanks!


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by huglester** [comment]
@RyanThompson actuallly I am getting this: http://pic.webas.lt/webas.lt-dY4qAJ7csl.png
do you know of an issue why this could be?

Thanks

**Comment by RyanThompson** [comment]
In the base composer package you need to keep laravel / illuminate html as is with the  VCS repositories as well: https://github.com/anomalylabs/streams/blob/master/composer.json#L14 <https://github.com/anomalylabs/streams/blob/master/composer.json#L14>


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by huglester** [comment]
yeah, that is how it was mean to be. and I did not touch this :/

and laravel/framework - did install ok
but illuminate/html does not, still trying to figure out what could cause this...

**Comment by huglester** [comment]
Ryan, I can't build this using simple changes to: prefer-stable: true,

and here what I get: http://pic.webas.lt/0U7YMBwnHN.png

but the problem is not with that textarea plugin, or something, if I remove it, it stops 1 step earlier...
Maybe it is trying to do something, when ll pakcages are downloaded?
I'm quite lost here now.

I tried to apply my changes to platform using:
```json
        {
            "type": "vcs",
            "url": "git@github.com:huglester/streams-platform.git"
        },
```
but same problem exists.


I have a feeling, that there is a package, which tries to remove something, and is not able to..

https://github.com/anomalylabs/addon-composer-plugin/blob/master/composer.json - btw here illuminate support required is 4.2, while streams-platform requires "illuminate/support": "5.0.*",

**Comment by RyanThompson** [comment]
Push to your fork and show me the composer file you’re using.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by huglester** [comment]
was afk, sorry.
here you got: https://github.com/huglester/streams/commit/c39905756bdeee0409d8c205106da2a656093f09

I moved themes to required, since I would get:
exception 'ReflectionException' with message 'Class Anomaly\StreamsTheme\StreamsTheme does not exist' in D:\code\pyro.app\vendor\laravel\framework\src\Illuminate\Container\Container.php:745

if using composer install with --no-dev
