### ISSUE TITLE
Flash/Validation Messages Not Working

### ISSUE THREAD

**Issue by BubeCPH** [anomalylabs/streams#127]

**Comment by RyanThompson** [comment]
Hmm, this looks like an issue with flash messages. I spent a bit of time just now looking at this because the did work. The session data just isn't there right now, I am not sure. Updating title.

**Comment by RyanThompson** [comment]
If that shop URL is converted to a string or has a valid URL input, it'll save.

**Comment by RyanThompson** [comment]
The UI component routes didn't specify a middleware group to passthrough and there was no default fallback to web - so no session data. Fixed! Now we can see what the heck is going on.

**Comment by RyanThompson** [comment]
https://github.com/laravel-streams/streams-ui/commit/84979779df659f707294073acd7bd8d75d037493
