### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by ramon-villain** [anomalylabs/streams#14]
When I try to install I'm getting this error, the Less' class seems the source…

**Comment by sektonic** [comment]
Try run the command "composer update" inside your cloned directory

**Comment by RyanThompson** [comment]
Refresh pages - it only compiles when not already compiled so eventually it will be done but that’s a LONG time.. Usually takes about 5 seconds the first time.

Or use the build download from the recent blog post.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581
