### ISSUE TITLE
Error in RoleModel.php while extending class

### ISSUE THREAD

**Issue by dakshhmehta** [anomalylabs/streams#15]
I got an error installing fresh stream from this repository to test out new features, but while composer install, I get following error:

Class 'Anomaly\Streams\Platform\Model\Users  
  \UsersRolesEntryModel' not found in /home/daksh/public_html/lab/pyrocms/cor  
  e/anomaly/users-module/src/Role/RoleModel.php on line 14 

I'm pretty sure @RyanThompson have already solved it, but just to point out of its missed while working on already installed copy

**Comment by RyanThompson** [comment]
This has been fixed in the build.
