### ISSUE TITLE
add composer.lock and maybe use stable versions where possible?

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams#18]
Hello,

I know PyroCMS 3 is still in dev, but since it is approaching the BETA, maybe it would be better to ship more stable defaults?

For example all packages are installed from branches, maybe it would be better to stick to tags?
because now we have: - Installing symfony/translation (2.6.x-dev bd939f0)
would not it be better to use 2.6.\* ? 

Probably adding `prefer-stable: true` to composer.json would partially solve this problem.

Another thing, in my opinion it would be good to  shipt composer.lock file. It have few benefits:
1) install will take far less time (since composer do not need to sncan anything and install the version required directly)

2) it would minime % of bugs, since we would be installing version of package developers have used, which also eliminates some points of failure..

Thanks :)

**Comment by huglester** [comment]
@RyanThompson hello, I am still returning with similar problem..
cloning pyrocms/pyrocms and doing composer install, installs symfony package sfrom 2.8.x/develop--- I think it is really bad idea, we sould stick to 'stable ones'? Like 2.7.x or something? those, which are 'tagged' and not from the branch, which may rise so many bugs

**Comment by RyanThompson** [comment]
Hey man - I'm getting close to handling this. Locking down versions all 'er day ^_^

Sent from my iPhone

On Jul 17, 2015, at 8:01 AM, huglester <notifications@github.com<mailto:notifications@github.com>> wrote:

@RyanThompsonhttps://github.com/RyanThompson hello, I am still returning with similar problem..
cloning pyrocms/pyrocms and doing composer install, installs symfony package sfrom 2.8.x/develop--- I think it is really bad idea, we sould stick to 'stable ones'? Like 2.7.x or something? those, which are 'tagged' and not from the branch, which may rise so many bugs

##

**Comment by RyanThompson** [comment]
You right :-)
