### ISSUE TITLE
An empty markdown file throws an fread error.

### ISSUE THREAD

**Issue by Pixney-William** [anomalylabs/streams#46]
https://flareapp.io/share/xPQ4orm1?owner_token=iLoOZfc1v8VxIwheqsKZ7QcJa5lZzCf3

**Comment by Pixney-William** [comment]
It does not only affect on that doc/page, it's globally.

**Comment by Pixney-William** [comment]
i would suggest throwing a 404 here for now?

**Comment by RyanThompson** [comment]
This appears to be an error in the Filesystem in Laravel. It can't fread 0byte files. A space, dot, anything fixes that issue. Not sure what I can do there. Closing as out of reach I guess.
