### ISSUE TITLE
Documentation Notes

### ISSUE THREAD

**Issue by fryiee** [anomalylabs/streams#47]
# Streams Documentation
### Introduction
- [x] The Streams platform is a new breed of CMS. is duplicated on the first and second line.
- [ ] I think calling it a data management system (DMS) without further elaboration might be a bit risky. There is an existing body of definitions for that, so it might be worth providing a bit more of  our own explanation as to _how_ it enables management of data.
- [x] While I do like the colloquial nature of "you can choose your adventure", I think it might be better off tightening this up to say something along the lines of "Streams is separated into individual packages so you can pick the feature set that bests suits your project."
- [x] Use cases. I think it might be worth having some more information around _why_ these use cases are well suited. We don't have to say why it's better than X, just an elevator pitch feature that helps sell it to people who have come here from search engines.
- [ ] I'm assuming the "Popular Resources" will grow? And will this exist entirely of first-party documentation links or also third party ones? If the latter, we may need to consider a more robust organisational system for them.

### Requirements
- [ ] Tech Specs - "Streams is a self-hosted PHP 7 application, designed as Composer packages for Laravel." - change in pluralisation. Should say "Streams is a self-hosted PHP 7 application delivered within a set of Composer packages for use with Laravel."
- [x] "Templating is, of course, powered by Blade." - I think we can drop the "of course", because for migrators, they could feasibly see us continuing to use Twig. If so, the of course is weirdly snarky in a way.
- [x] Supported Image Libraries - we should make it clear if you need one or the other, or both, or if they are mutually exclusive.

### Installation
- [x] Within "create a blank project", we should specify which Streams packages are pre-installed (Core/UI/API).
- [x] "Installing Streams" - as cute as this is, I think it sort of needlessly clutters this page a bit. Especially because further up it explicitly says "Streams can be installed...". So I think we're better off just removing this section entirely or modifying it to say "Your streams project is now ready for you to start coding. Dive into next steps below" or something like that.

### Configuration
✓

### Debugging
- [x] "The debug bar comes with the Streams platform as a development dependency by default." - We should change to say "if you created a blank Streams project, the debug bar is added as a development dependency by default.", just to reinforce that adding to existing projects won't bring it in (unless it's a dev dependency on one of the packages? if so, we need to note it)

### Contributing
- [ ] Contribution Guide spacing and sizing seems off here.
- [x] Which Repository? "Please send all issues to the base anomalylabs/streams repository" - is this going to be the repo still moving forward?

### API Readiness
- [x] This feels a bit barebones, but I'm struggling to think of what else could go here so it's probably fine.

# Core Documentation
### Configuration 
- [ ] This is identical to to the Streams config page - intentional?

**Comment by RyanThompson** [comment]
On the use cases - those will inevitably be links to a page that outlines how that use case is best suited with streams and such.

**Comment by RyanThompson** [comment]
Popular Resources are mostly ours at this time and some outside links. I don't suspect it'll ever be more-than-not, third party resources.

**Comment by RyanThompson** [comment]
Haha it IS snarky.. both to my old thoughts on the matter and also competitors' decision to also turn away from Blade for equally not good reasons lol
